### ISSUE TITLE
Link specific users to individual loans

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#188]
Collection managers will have loans to manage across several collections, and external researchers will be associated with certain loans. We want a way for both collection managers and external researchers to be able to access and modify the loans that they are assigned to (with appropriate permissions for the external people). This will facilitate easier loan management and will facilitate the addition of value-added data by researchers using samples.

**Comment by kyule** [comment]
@mandrewj What do you think about this one at this point? Would this make a tangible difference on the management side?  If it only really helps with the external researcher side of things, I vote to close as I now see it as unlikely to be used enough to warrant development.

**Comment by mandrewj** [comment]
I don't think we want external folks to edit our loans at all - that should be on our end.

We might run into issues in the future since loans are linked to "institutions" and not "individuals" so we might need to make a protocol where we make a new "institution" entry in the database for every PI that works with us so that it is immediately obvious in the loan management process.

But that shouldn't really need development right now

**Comment by kyule** [comment]
@mandrewj Agree 100%
