### ISSUE TITLE
Family and author are inconsistently displayed in table view of returned mammal voucher occurrence records

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#363]
When viewing search results for mammal vouchers in table view, family is missing for some records (but visible for others) and the author is inconsistently applied.

Example: Search for records within any or all of the mammal voucher collections (although it is more obvious in the standard sampling mammal voucher collection --> NEON-MAMC-VSS). Display records in table view. Notice that the family name is missing for some records and not others. The author name is also displayed inconsistently (e.g. both _Myodes rutilus_ Pallas and _Myodes rutilus_ (Pallas, 1779) are shown). 
![image](https://github.com/BioKIC/NEON-Biorepository/assets/55719283/cfc7cdd2-2794-4182-b966-54b009c8ca85)
![image](https://github.com/BioKIC/NEON-Biorepository/assets/55719283/6eabfedb-d24b-4e4b-9291-924c358beb01)

**Comment by kyule** [comment]
Hmmm. This is hard to diagnose. It isn't an issue with what is being published in the NEON API, since that is just a taxonCode that should be being translated during harvesting. For example in the NEON API MYRU has Pallas only. In our portal we have MYRU associated with (Pallas, 1779). So I could see either way happening, but don't understand why it would be inconsistent.

**Comment by sunray1** [comment]
Family and scientificNameAuthorship are pulled from the current determination.

Missing family is due to family field missing in current determination. 
scientificNameAuthorship is different in current determinations across samples. 

I imagine this is likely due to different versions of the taxonomy or something over time - reharvesting standardizes them, but I did notice that the current version of the taxonomy is missing the years in scientificNameAuthorship for some (so reharvesting a Sorex cinereus Kerr, 1792 will change to Sorex cinereus Kerr)

The missing family issue has to do with the fact that when @lsteger or Rosie update the determinations, it doesn't update the determination family, only the occurrence family.

**Comment by kyule** [comment]
@lsteger Bumping this in case you didn't see Chandra's comment above. We can definitely fix the current determinations and we should be able to update the table that determines what will come in with harvesting to whatever you prefer. Happy to meet about this!

**Comment by lsteger** [comment]
Thanks Chandra and Kelsey. Let me put together a cleaned up mammal taxonomy file that we can use.

**Comment by lsteger** [comment]
[MDD_v1.12.1_6718species.csv](https://github.com/BioKIC/NEON-Biorepository/files/14349751/MDD_v1.12.1_6718species.csv)

Attached is a .csv file with the most up-to-date taxonomic names (and authors) for mammals in the US. This file is a subset of the larger database developed by the American Society of Mammalogists. There is a field in the file called authorityParentheses that indicates whether or not the authority should be in parentheses or not. This file contains a lot of additional information (e.g. common name) and it would be great to be able to import as much of this information as possible (or relevant) into the taxonomic thesaurus. Let me know if you have questions. Thank you!

**Comment by sunray1** [comment]
@kyule I can update the taxonomy tables - do you want me to manually fix the occurrence names or would you prefer to mass reharvest?

**Comment by kyule** [comment]
@sunray1 Thank you! I think we can rehavest but I'll want to test a couple first to make sure it's working like I'd want/expect before going full scale.

**Comment by sunray1** [comment]
@kyule okay, the authorship part should be good to go.

**Comment by sunray1** [comment]
I've fixed the missing family fields and added family to determination edits, so moving forward it will be included.

**Comment by lsteger** [comment]
Woohoo!! Thank you so much!

**Comment by sunray1** [comment]
Symbiota team is working on redesigning the determinations module and hopes to have that integrated into NEON by the end of next week. If that is not integrated by March 1 we will merge this branch in as a fix until it is.

**Comment by kyule** [comment]
@lsteger I'm currently reharvesting all of the mammal samples. Once that's finished, you should not see issues with the author formating because of Chandra's efforts. I believe we will need to add the families into the current determinations manually in the back end for ones made in the past, but once this Symbiota update is made, family should be added automatically when you input a new determination.
