### ISSUE TITLE
Errors in determination harvesting in macroalgae point count samples

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#407]
Determinations are not correctly harvesting for the attached samples in AMAC-CCPC. For some it seems that the taxon is not coming in at all and for others it is but correct date is never coming in so actual ID is not always being labeled as current. 

[AMAC-CCPCDeterminationIssues.csv](https://github.com/BioKIC/NEON-Biorepository/files/14225165/AMAC-CCPCDeterminationIssues.csv)

Note that a few of these are also no longer harvesting at all and I don't (errorMessage of not being found in API), but spot checking shows them in the API so I do not know why that is occurring.

Note that I also did not check whether harvesting is still working well for other samples in this collection that currently do have correct determinations, but given that this issue is happening with both old and new samples, it seems unlikely that it is due simply to a change in the API.

**Comment by kyule** [comment]
Something must have changed because the majority of issues reported above are no longer relevant. However, there are still a number of samples that no longer harvest for this collection. Spot checking the samples does show them coming up in the sample explorer, so I'm not sure why this would be happening. This query produces the samples in question: SELECT * FROM NeonSample
WHERE errorMessage LIKE '%API%' AND sampleClass='apc_perTaxon_in.sampleIDmacroalgae';

**Comment by sunray1** [comment]
Quick note - all of these do have associated occurrences already. Though idk why reharvesting is throwing this error yet.

**Comment by sunray1** [comment]
The harvester searches for the identifiers in this order (but assumes that if an ID exists, it will have data via the API, will return an error and stop searching if it does not):

1. Barcode/sampleCode
2. SampleUUID
3. archiveGuid/occurrenceID/catalogNumber
4. sampleID/sampleTag

**Comment by sunray1** [comment]
These all have the issue where the sampleUUID returned by the archiveGuid is different than what we have in our records.

i.e. https://data.neonscience.org/api/v0/samples/view?archiveGuid=NEON01DHJ returns a sampleUUID of 'edbf7010-14a2-4187-85e8-7278828bb3fd' where we have 'b103d3c1-5356-4d85-a49a-1e3c08965273' in our occurrence [record](https://biorepo.neonscience.org/portal/collections/editor/occurrenceeditor.php?occid=463935).

The way the logic in the harvester was set up, it was trying to search the API using the SampleUUID that we have in our record, but then returning a 'not being found in the API' when that returned with no data without searching any other identifiers. I've changed the logic so that it will search all the identifiers before returning errors. The proper error will now show up. (i.e. "ABORT: DATA ISSUE: sampleUuid failing to match (old: b103d3c1-5356-4d85-a49a-1e3c08965273, new: edbf7010-14a2-4187-85e8-7278828bb3fd)")
