### ISSUE TITLE
Microalgae groups not being returned in search for "Algae"

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository#409]
Microalgae are not being returned in a search for the taxon "Algae" even though the records are associated with correct taxonIDs and the higherTaxonomy looks correct with Algae as a higher taxon. 

https://biorepo.neonscience.org/portal/collections/list.php?db=61%2C22%2C53%2C48%2C57%2C21%2C62%2C45%2C60%2C50%2C73%2C9%2C7%2C8%2C92%2C41%2C30%2C76%2C10%2C42%2C67%2C5%2C31%2C69%2C68%2C6%2C47%2C46%2C49%2C84%2C93%2C81%2C11%2C63%2C39%2C14%2C13%2C16%2C85%2C56%2C65%2C59%2C29%2C4%2C75%2C18%2C54%2C40%2C23%2C66%2C20%2C12%2C15%2C70%2C24%2C71%2C25%2C26%2C27%2C91%2C90%2C17%2C19%2C28&includeothercatnum=1&taxa=Algae&usethes=1&taxontype=1

<img width="1226" alt="image" src="https://github.com/BioKIC/NEON-Biorepository/assets/4763928/96cb84be-a5f5-45ff-9101-268b7b046a63">

However when I search with "include synonymns" unchecked, I seem to get the microalgae and do not get the macroalgae. https://biorepo.neonscience.org/portal/collections/list.php?db=61,22,53,48,57,21,62,45,60,50,73,9,7,8,92,41,30,76,10,42,67,5,31,69,68,6,47,46,49,84,93,81,11,63,39,14,13,16,85,56,65,59,29,4,75,18,54,40,23,66,20,12,15,70,24,71,25,26,27,91,90,17,19,28&taxa=Algae&taxontype=1&page=78

I seem to have loaded these "pseudotaxa" into the taxonomic hierarchy incorrectly, but am not sure how to fix the issue.

**Comment by sunray1** [comment]
This is due to a bug where when "include synonyms" is checked for an unaccepted, higher level taxa (above family), the original search term and its children are not included, only the synonyms and their children (and their synonyms) (note: no 'Taxonomic Group: Algae" is included below). So only the [accepted names](https://biorepo.neonscience.org/portal/taxa/taxonomy/taxoneditor.php?tid=126825) of Algae, which look to be all linked to just 'Algae', 'Macroalgae' or 'Algae and macroalgae', are showing up.

![image](https://github.com/BioKIC/NEON-Biorepository/assets/21106063/315d3b9b-dd44-441c-b1ff-41db957d18a1)

When "included synonyms" is unchecked, the original search term is searched, along with its children (and their children, but not their synonyms.). There is only one '[Macroalgae](https://biorepo.neonscience.org/portal/collections/individual/index.php?occid=463925)' specimen right now, and 'Macroalgae' has [no children](https://biorepo.neonscience.org/portal/taxa/taxonomy/taxoneditor.php?tid=126826) so it stops there. There are [three children](https://biorepo.neonscience.org/portal/taxa/taxonomy/taxoneditor.php?tid=126827) in 'Microalgae' - 'Periphyton', 'Phytoplankton' and 'Seston', which is what you're seeing. 

I'm not entirely sure what the distinction is between accepted taxa and children taxa in these psuedotaxa or how that's used, but fixing the error mentioned above gives you the original search term, its children and their synonyms, and its synonyms and their children when searching with "include synonyms" is checked, which I think is the expected behavior.
