### ISSUE TITLE
Determinations in download file not matching determination in portal

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#512]
Urgent! At least for some samples/collections, the occurrence record download file (.csv) contains the old determination instead of the current determination. See NEON011F7 as an example.

**Comment by sunray1** [comment]
This is because for some reason, the determination information in the omoccurrence table is different from the current accepted determination in omoccurdetermination. Here's the list of records that have only one current determination where the data is different. 

[records_with_different_current_dets_singular.csv](https://github.com/user-attachments/files/16317677/records_with_different_current_dets_singular.csv)

@kyule - we need to deal with the records that have multiple current determinations:

(SELECT occid, COUNT(*) as current_count
FROM omoccurdeterminations
WHERE iscurrent = 1
GROUP BY occid
HAVING COUNT(*) > 1;)

**Comment by sunray1** [comment]
Look at the above data, I'm only fixing a few of the blatant records:

[records_with_different_scinames_singular.csv](https://github.com/user-attachments/files/16317720/records_with_different_scinames_singular.csv)

**Comment by kyule** [comment]
@sunray1  For the ones with multiple current determinations,  I was able to resolve almost all of them. Most of those were due to the legacy of issues related to taxon protections. The only remaining ones have both a legitimately protected IDs and the fuzzed ID listed as current. I'm not sure how those are supposed to be addressed, so I haven't touched them yet.  LMK...
[allDetsWithMultiples.csv](https://github.com/user-attachments/files/16369270/allDetsWithMultiples.csv)

**Comment by kyule** [comment]
Sorry kind of confusing that I'm closing the other issue and re-opening this one -- just seems like an easier way to keep Laura in the loop. Excepting those individuals in the above comment, I one-by-one investigated and updated all instances in which the current determination tid != occurrence record tid. That should solve a lot of issues, but Laura let me know if you find more issues. It's possible there could be other mismatches.

**Comment by kyule** [comment]
FWIW - I also went through and cleaned up all the instances in which the current determination sciname and occurrence sciname are not equal, except for the above cases and collid 30 which (low priority since it's soils) needs some more major help.

**Comment by sunray1** [comment]
Thanks for all the data slogging here @kyule

**Comment by kyule** [comment]
No problem -- in situations with a protected taxon should they have both a fuzzed and a protected determination and should both be "current"?

**Comment by kyule** [comment]
Figured it out. Only one determination should exist!
