### ISSUE TITLE
Label printing tool has formatting issue

### ISSUE THREAD

**Issue by lsteger** [BioKIC/NEON-Biorepository#516]
Trying to print some labels and only some of them are displaying properly (see screenshot; the upper left label is correct, all others are displaying incorrectly). I'm using the Mammal (Wet) Label.

![image](https://github.com/user-attachments/assets/fa68bbca-28f4-45cd-aaff-43ffc4def61d)

**Comment by lsteger** [comment]
Looks like a combination of things might be causing this. The Perognathus inornatus doesn't have a catalog number so that is one reason that particular label might be formatting incorrectly. NEON09G0A and NEON09G0B are displaying the catalog number as the barcode, instead of the NEON barcode and are displaying the dynamic properties field---not sure why.

**Comment by kyule** [comment]
@lsteger The reason why these formatting issues tend to happen is because of something messed up in the actual data. Eg. I've seen a missing parenthesis after the ORCID lead to all of the downstream fields being wonky. I believe it can even mess up the following records in the print queue. When I gave the one with no catalog number a fake number, it seems to fix all of them at least at first glance: 

<img width="749" alt="image" src="https://github.com/user-attachments/assets/ec42b358-aaf8-4671-8c03-0545f9b3ce32">

So I think that is all that's wrong here; however, it's strange that this individual is not coming up in the list of samples for which an IGSN needs to be assigned. I'll look into that more and see if it's a larger scale issue ASAP.

**Comment by sunray1** [comment]
^^ lmk if any help dealing with the js behind this is needed - i remember this code being slightly buggy in general

**Comment by kyule** [comment]
@sunray1 it's maybe kind of nice to have an extra check on the data quality like this, but if there was an obvious way to make one messed up label not ruin all the others on the page, that would probably be cool. We've always been able to diagnose the issues, so maybe not worth retooling until another significant one comes up.

**Comment by kyule** [comment]
The issue with individuals not showing up for IGSN assignment is fixed with #523. Assigning the ones that had been missed now.
